AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Example Hello world Lambda function written with SpringBoot to showcase SnapStart.

Globals:
  Function:
    Timeout: 20
Resources:
  NISnapStartDemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.numericaideas.snapstart.Handler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      Events:
        HttpApiEvent:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NISnapStartDemoFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/hello"
  NISnapStartDemoFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt NISnapStartDemoFunction.Arn
  NISnapStartDemoFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt NISnapStartDemoFunctionRole.Arn
